/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AppointmentUpdateManyWithoutUsersInput } from "./AppointmentUpdateManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { BlogUpdateManyWithoutUsersInput } from "./BlogUpdateManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserSubscriptionUpdateManyWithoutUsersInput } from "./UserSubscriptionUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AppointmentUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AppointmentUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AppointmentUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  appointments?: AppointmentUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => BlogUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => BlogUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => BlogUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  blogs?: BlogUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  role?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => UserSubscriptionUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserSubscriptionUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserSubscriptionUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  userSubscriptions?: UserSubscriptionUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
